language: android

git:
  depth: 9999999

branches:
  only:
    - master

android:
  components:
  - tools
  - build-tools-28.0.0
  - android-28

jdk:
- oraclejdk8

before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"

script:
- "./gradlew assembleRelease"
- gem install fir-cli

after_script:
- fir login $fir_token
- fir p app/build/outputs/apk/release/app-release.apk -c "$TRAVIS_COMMIT_MESSAGE"